### PR TITLE
Attempting to calculate and display distance.

### PR DESCRIPTION
**Pull request by nmisyel**
I can't seem to get it to work. Any suggestions?

### CODE REVIEW

**Comment by rahat** [comment]
It seems like it's working - I just need to add runActivity to the manifest to get it running in the emulator & design editor.
cal

**Comment by rsaddler** [comment]
Should I remind Belodine that she is working in the settings page

On Saturday, May 9, 2015, Rahat Mahmud notifications@github.com wrote:

> Merged #2 https://github.com/rahatmahmud/RoadRunner/pull/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rahatmahmud/RoadRunner/pull/2#event-300877574.

## 

Best Regards
Radcliffe Saddler

## 

---

This email message is from a student email account at Pathways in 
Technology Early College High School (P-TECH). Please use this link to find 

## P-TECH's contact information: www.ptechnyc.org

**Comment by rahat** [comment]
@rsaddler Yeah that would be a good idea.

**Comment by nmisyel** [comment]
Oh I see - let me round the result to 2 decimal places and add units.

**Pull request merged**
